theme = "gruvbox"

[editor]
cursorcolumn = false
cursorline = true
idle-timeout = 250
line-number = "relative"
rulers = [80, 100]

[editor.indent-guides]
character = "|"
skip-levels = 1
render = true

[editor.lsp]
display-messages = true

[editor.smart-tab]
supersede-menu = true

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
newline = "all"
tab = "all"

# Keybindings
[keys.insert]
"C-[" = "normal_mode"
"j" = { j = "normal_mode" }

[keys.normal.A-b]
c = ":buffer-close"
n = ":buffer-next"
p = ":buffer-previous"
# c = { command = ":buffer-close", label = "Close buffer" }
# n = { command = ":buffer-next", label = "Next buffer" }
# p = { command = ":buffer-previous", label = "Previous buffer" }

[keys.normal.A-c]
o = ":config-open"
r = ":config-reload"
w = ":config-open-workspace"
# o = { command = ":config-open", label = "Open config" }
# r = { command = ":config-reload", label = "Reload config" }
# w = { command = ":config-open-workspace", label = "Open workspace config" }

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
W = ":write"
# W = { command = ":write", label = "Save file" }

[keys.normal]
"A-i" = ":toggle-option lsp.display-inlay-hints"

