live_config_reload = true

import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[cursor]
style = { blinking = "On", shape = "Underline" }

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.offset]
x = 0
y = -1

[window]
resize_increments = true
